apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mcl9sg820-go
  janus-idp.io/tekton: mcl9sg820-go
  backstage.io/kubernetes-id: mcl9sg820-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mcl9sg820-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
