apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mcl9sg820-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mcl9sg820-go 
  name: mcl9sg820-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mcl9sg820-go 
